site_name: Pyright for PyCharm
site_description: A PyCharm plugin that runs Pyright as you code
site_url: https://insyncwithfoo.github.io/pyright-for-pycharm

repo_name: InSyncWithFoo/pyright-for-pycharm
repo_url: https://github.com/InSyncWithFoo/pyright-for-pycharm

edit_uri: blob/master/docs/

exclude_docs: |
  /requirements.txt

theme:
  name: material
  favicon: img/icon.svg
  logo: img/icon-outline-10-white.svg
  palette:
    -
      media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: octicons/sun-16
        name: "Switch to dark mode"
    -
      media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: octicons/moon-16
        name: "Switch to light mode"
  features:
    - content.action.edit

markdown_extensions:
  - admonition:
  - codehilite:
  - toc:
      permalink: '#'

nav:
  - Overview: index.md
  - Configurations: configurations.md
  - FAQ: faq.md

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn

strict: true
